---
- name: Deploy Prometheus Stack
  hosts: kubernetes
  gather_facts: false
  tasks:
    - name: Add prometheus-community helm repo
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts

    - name: Create monitoring namespace
      kubernetes.core.k8s:
        name: monitoring
        api_version: v1
        kind: Namespace
        state: present

    - name: Deploy kube-prometheus-stack
      kubernetes.core.helm:
        name: prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: monitoring
        create_namespace: true
        values:
          grafana:
            service:
              type: LoadBalancer
            adminPassword: admin123  # Change this in production
            dashboardProviders:
              dashboardproviders.yaml:
                apiVersion: 1
                providers:
                - name: 'default'
                  orgId: 1
                  folder: ''
                  type: file
                  disableDeletion: false
                  editable: true
                  options:
                    path: /var/lib/grafana/dashboards
            dashboards:
              default:
                mongodb:
                  gnetId: 2583  # MongoDB Overview
                  revision: 1
                  datasource: Prometheus
                kubernetes:
                  gnetId: 13332  # Kubernetes Metrics
                  revision: 1
                  datasource: Prometheus
          prometheus:
            service:
              type: LoadBalancer
            prometheusSpec:
              serviceMonitorSelectorNilUsesHelmValues: false
              podMonitorSelectorNilUsesHelmValues: false
              ruleSelectorNilUsesHelmValues: false
