serviceMonitors:
  - name: backend
    labels:
      release: prometheus
    namespaceSelector:
      matchNames:
        - default
    endpoints:
      - port: http
        interval: 15s
    selector:
      matchLabels:
        app: backend

  - name: mongodb
    labels:
      release: prometheus
    namespaceSelector:
      matchNames:
        - default
    endpoints:
      - port: mongodb
        interval: 30s
    selector:
      matchLabels:
        app: mongodb

dashboards:
  mongodb:
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server
        isDefault: true
    
  kubernetes:
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server
        isDefault: true

alerting:
  rules:
    - name: HighCPUUsage
      rules:
        - alert: HighCPUUsage
          expr: container_cpu_usage_seconds_total > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            description: Container {{ $labels.container }} has high CPU usage
            
    - name: HighMemoryUsage
      rules:
        - alert: HighMemoryUsage
          expr: container_memory_usage_bytes > 1024 * 1024 * 1024  # 1GB
          for: 5m
          labels:
            severity: warning
          annotations:
            description: Container {{ $labels.container }} has high memory usage
