server:
  service:
    type: LoadBalancer
  
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - argocd.local

  config:
    repositories: |
      - url: https://github.com/MariammBello/ecomm.git
        name: ecomm
        type: git

    credential.templates: |
      - url: ghcr.io
        username: MariammBello
        password: ${GITHUB_TOKEN}

  additionalApplications:
    - name: ecomm
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/MariammBello/ecomm.git
        targetRevision: HEAD
        path: k8s/on-premise
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

configs:
  secret:
    createSecret: true
    githubToken: ${GITHUB_TOKEN}
